"""Inference Response Schema.

Author: DriftAdapt Contributors
Purpose: Defines the structure returned to the client after a generation run.
"""

from typing import Optional, Dict, Any
from pydantic import BaseModel, Field
import time

from app.schemas.token_usage import TokenUsage


class InferenceResponse(BaseModel):
    """The final API payload sent back to a requester."""
    
    success: bool = Field(default=True, description="Indicates if the request succeeded")
    generated_text: str = Field(default="", description="The output text generated by the LLM")
    adapter_used: Optional[str] = Field(default=None, description="The adapter ID used for generation, if any")
    inference_time: float = Field(default=0.0, description="Total server-side processing time (seconds)")
    prompt_tokens: int = Field(default=0, description="Number of tokens in the prompt")
    completion_tokens: int = Field(default=0, description="Number of tokens generated")
    total_tokens: int = Field(default=0, description="Total tokens consumed")
    generation_parameters: Dict[str, Any] = Field(default_factory=dict, description="The actual parameters used (including fallbacks)")
    finish_reason: str = Field(default="stop", description="Why generation halted (e.g. 'stop', 'length', 'timeout')")
    timestamp: float = Field(default_factory=time.time, description="Unix timestamp of response creation")
