"""Token Usage Schema.

Author: DriftAdapt Contributors
Purpose: Tracks inference tokenizer footprint for cost estimation and telemetry.
"""

from pydantic import BaseModel, Field


class TokenUsage(BaseModel):
    """Tracks token consumption per inference request."""
    
    prompt_tokens: int = Field(default=0, description="Number of tokens in the formatted prompt")
    completion_tokens: int = Field(default=0, description="Number of tokens generated by the model")
    total_tokens: int = Field(default=0, description="prompt_tokens + completion_tokens")
    estimated_cost: float = Field(default=0.0, description="Estimated computational cost (e.g., USD based on API pricing equivalent)")
    throughput: float = Field(default=0.0, description="Tokens generated per second (completion_tokens / latency)")
