"""DriftAdapt Metric Schema Module.

Author: DriftAdapt Contributors
Purpose: Strictly models structured metric records using Pydantic validation.
Future Integration: Generated by publishers and processed by store, registry, and exporters.
"""

import time
from typing import Any, Dict, List, Optional, Union
from pydantic import BaseModel, Field


class Metric(BaseModel):
    """Pydantic model representing a structured telemetry event."""

    name: str = Field(
        ...,
        description="The identifying name of the metric (e.g., 'val_loss', 'cpu_usage')."
    )
    value: Union[float, int, bool, str, List[Any]] = Field(
        ...,
        description="The recorded metric value. Supports floats, ints, bools, strings, and lists."
    )
    timestamp: float = Field(
        default_factory=time.time,
        description="POSIX epoch timestamp of when the metric was generated."
    )
    module: str = Field(
        ...,
        description="The originating module name (e.g. 'FoundationModel', 'ClinicSimulator')."
    )
    step: Optional[int] = Field(
        default=None,
        description="The optional optimization step count."
    )
    round: Optional[int] = Field(
        default=None,
        description="The optional federated communication round count."
    )
    client_id: Optional[str] = Field(
        default=None,
        description="The optional client node identifier (e.g. 'client_001')."
    )
    experiment_id: Optional[str] = Field(
        default=None,
        description="The identifying name of the active experiment sweep."
    )
    metadata: Dict[str, Any] = Field(
        default_factory=dict,
        description="Optional unstructured dictionary containing additional execution context."
    )
