"""DriftAdapt Adaptation Schema.

Author: DriftAdapt Contributors
"""

import time
import uuid
from typing import Dict, Any, List, Optional
from pydantic import BaseModel, Field


class AdaptationDecision(BaseModel):
    """Represents a discrete adaptation decision generated by the engine."""
    decision_id: str = Field(default_factory=lambda: str(uuid.uuid4()))
    timestamp: float = Field(default_factory=time.time)
    
    # Context
    drift_reports: List[str] = Field(default_factory=list) # IDs or references
    affected_clinics: List[str] = Field(default_factory=list)
    
    # Decision Details
    adaptation_required: bool
    policy_name: str
    priority: str # LOW, MEDIUM, HIGH, CRITICAL
    urgency: str  # IMMEDIATE, NEXT_ROUND, DEFERRED, MANUAL
    confidence: float
    
    # Justification
    justification: str
    metadata: Dict[str, Any] = Field(default_factory=dict)
